// ============================================================================
// rf-fluxmacro — Markdown Reporter
// ============================================================================
// FM-16: Markdown report generator.
// ============================================================================

use crate::context::{MacroContext, ReportFormat};
use crate::error::FluxMacroError;
use crate::reporter::Reporter;

/// Markdown report generator.
pub struct MarkdownReporter;

impl Reporter for MarkdownReporter {
    fn format(&self) -> ReportFormat {
        ReportFormat::Markdown
    }

    fn generate(&self, ctx: &MacroContext) -> Result<Vec<u8>, FluxMacroError> {
        let mut md = String::with_capacity(4096);

        // Header
        let status = if ctx.is_success() { "PASS" } else { "FAIL" };
        md.push_str(&format!("# FluxMacro Report — {}\n\n", ctx.game_id));
        md.push_str(&format!("**Status:** {status}\n"));
        md.push_str(&format!(
            "**Duration:** {:.1}s\n",
            ctx.duration().as_secs_f64()
        ));
        md.push_str(&format!("**Seed:** {}\n", ctx.seed));
        if !ctx.run_hash.is_empty() {
            md.push_str(&format!(
                "**Run Hash:** `{}`\n",
                &ctx.run_hash[..16.min(ctx.run_hash.len())]
            ));
        }
        md.push_str("\n---\n\n");

        // QA Results
        if !ctx.qa_results.is_empty() {
            md.push_str("## QA Results\n\n");
            md.push_str("| Test | Status | Duration | Details |\n");
            md.push_str("|------|--------|----------|---------|\n");
            for qa in &ctx.qa_results {
                let status_icon = if qa.passed { "PASS" } else { "FAIL" };
                md.push_str(&format!(
                    "| {} | {} | {}ms | {} |\n",
                    qa.test_name, status_icon, qa.duration_ms, qa.details
                ));
            }
            md.push('\n');
        }

        // Artifacts
        if !ctx.artifacts.is_empty() {
            md.push_str("## Artifacts\n\n");
            let mut sorted: Vec<_> = ctx.artifacts.iter().collect();
            sorted.sort_by_key(|(name, _)| (*name).clone());
            for (name, path) in sorted {
                md.push_str(&format!("- **{}**: `{}`\n", name, path.display()));
            }
            md.push('\n');
        }

        // Warnings
        if !ctx.warnings.is_empty() {
            md.push_str("## Warnings\n\n");
            for w in &ctx.warnings {
                md.push_str(&format!("- {w}\n"));
            }
            md.push('\n');
        }

        // Errors
        if !ctx.errors.is_empty() {
            md.push_str("## Errors\n\n");
            for e in &ctx.errors {
                md.push_str(&format!("- {e}\n"));
            }
            md.push('\n');
        }

        // Summary metrics
        md.push_str("## Summary\n\n");
        md.push_str(&format!("- **Total Logs:** {}\n", ctx.logs.len()));
        md.push_str(&format!("- **Warnings:** {}\n", ctx.warnings.len()));
        md.push_str(&format!("- **Errors:** {}\n", ctx.errors.len()));
        md.push_str(&format!(
            "- **QA Tests:** {} passed, {} failed\n",
            ctx.qa_passed_count(),
            ctx.qa_failed_count()
        ));
        md.push_str(&format!("- **Artifacts:** {}\n", ctx.artifacts.len()));
        md.push_str("\n---\n\n");
        md.push_str("*Generated by FluxMacro Engine*\n");

        Ok(md.into_bytes())
    }

    fn file_extension(&self) -> &'static str {
        "md"
    }
}
